[package]
name = "cmake2mcpp"
version = "0.1.0"
license = "MIT"

[build]
defines = ['SPDLOG_COMPILED_LIB']


[dependencies]
marzer.tomlplusplus = "3.4.0"
nlohmann.json = "3.12.0"
CLI11 = { path = "./CLI11-2.7.2" }
spdlog = { path = "./spdlog" }
